### ISSUE TITLE
Main bandersnatch could implement this

### ISSUE THREAD

**Issue by cooperlees** [z4yx/bandersnatch-hack#2]
I’d be happy to take a PR for “bandersnatch sync package_name ...” CLI :) ... it’s a good idea.

Will open an issue on main bandersnatch ...

**Comment by cooperlees** [comment]
https://github.com/pypa/bandersnatch/issues/560

**Comment by z4yx** [comment]
I'm glad to help on this. This function is quite useful when I run the mirror site, because we occasionally receive user reports on the incomplete versions of some packages.

**Comment by z4yx** [comment]
Done!
